### ISSUE TITLE
reproduce eval metrics 

### ISSUE THREAD

**Issue by N950** [ibaiGorordo/HITNET-Stereo-Depth-estimation#3]
Hi I'm trying to reproduce the metrics reported here https://github.com/zjjMaiMai/TinyHITNet

When running ModelType.middlebury on cones/im2.png cones/im6.png the disparity_map looks close in visualisation
But it's values are maxed at ~55.0 and EPE metric is at ~98.0 when compared to cones/disp2.png

Could you please share the proper way to evaluate the model ?

**Comment by ibaiGorordo** [comment]
To be honest, I have not checked any of the evaluation metrics. The main objective of this repository is to provide an "easy" to use inference of the model. For the train/evaluation of the model, I would suggest to use the original repository or in this case, the tinyHITNet repository which also contains the evaluation code.

However, I have done a quick test, and I get an EPE of 0.52 using the for the cone image modifying the image example like this:
```
# Load images
left_img = load_img("https://vision.middlebury.edu/stereo/data/scenes2003/newdata/cones/im2.png")
right_img = load_img("https://vision.middlebury.edu/stereo/data/scenes2003/newdata/cones/im6.png")
left_disp = load_img("https://vision.middlebury.edu/stereo/data/scenes2003/newdata/cones/disp2.png").astype(np.float32)/4

# Estimate the depth
disparity_map = hitnet_depth(left_img, right_img)

print(evaluate(disparity_map, left_disp))
```

where evaluate is this function: https://github.com/google-research/google-research/blob/a300d0a4ed40e69c543269d60ae16f5ab498c5f2/hitnet/predict.py#L157

Did you divide the ground truth disparity by 4 as mentioned in the middlebury dataset? https://vision.middlebury.edu/stereo/data/scenes2003/

**Comment by N950** [comment]
@ibaiGorordo thanks for taking the time
No I wasn't dividing by 4, will fix my eval methods to reproduce this
Thank you for your help
