### ISSUE TITLE
imageDepthEstimation.py error

### ISSUE THREAD

**Issue by ynjiun** [ibaiGorordo/HITNET-Stereo-Depth-estimation#4]
Hi,

I tried to run "python imageDepthEstimation.py" and encounter the following error:

`NotImplementedError: Cannot convert a symbolic Tensor (PartitionedCall:0) to a numpy array.`

when I traced the code below:

```
        def inference(self, input_tensor):
		output = self.model(input_tensor)
		return np.squeeze(output)
```

and found that:
input_tensor: <tf.Tensor 'Const:0' shape=(1, 375, 450, 2) dtype=float32>
output: <tf.Tensor 'PartitionedCall:0' shape=(?, ?, ?, ?) dtype=float32>

It seems the model is not working!? (I did trace the model path are correct and loading the model went through without any error message...)

Could you please help to shed some insight on what caussing this problem? and how to fix it?

environemnt:
tensorflow: 1.15
python: 3.6.5
numpy: 1.19.5

Thanks.

**Comment by ibaiGorordo** [comment]
Hi, try using Tensorflow 2. Even though the model is Tensorflow 1, it will load be able to load it.

I have also added the requirements: `pip install -r requirements.txt`

**Comment by ynjiun** [comment]
@ibaiGorordo 

Thank you for your quick response. It works now! Great job!
