### ISSUE TITLE
About  generalization evaluation on Middlebury 2014

### ISSUE THREAD

**Issue by gangweix** [ibaiGorordo/HITNET-Stereo-Depth-estimation#5]
I found generalization of the HITNet to be extremely bad，I use the pretrained model on Scene Flow, whose EPE is 0.5. Can you give a reason?

**Comment by ibaiGorordo** [comment]
Not sure, since I only wrote the inference code. In my experience, the Middlebury version gives the best generalization (tested on the DrivingStereo dataset and other stereo cameras).
