### ISSUE TITLE
Tensorflow models

### ISSUE THREAD

**Issue by chaimaOues** [ibaiGorordo/HITNET-Stereo-Depth-estimation#6]
Hello, thank you for this code, i try to test imageDepthEstimation.py
i  did not find the Tensorflow models, can you please give me the link to download it .
thank you

**Comment by ibaiGorordo** [comment]
Check the readme:
https://github.com/ibaiGorordo/HITNET-Stereo-Depth-estimation#tensorflow-models

**Comment by chaimaOues** [comment]
thank you for your answer, i checked the readme but i didn't found the models
![Capture](https://user-images.githubusercontent.com/10595916/178014857-2427a554-78a4-4a95-b1c0-db0b1032db37.PNG)

**Comment by ibaiGorordo** [comment]
Check the .sh files, they contain the download link for each of the models.

You will have to replace the model name as shown below
![Imagen1](https://user-images.githubusercontent.com/43162939/178016071-9c17c968-b1b1-43c5-9e4c-d9d15c0a68e4.png)

**Comment by chaimaOues** [comment]
thank you very much for you help , it works  very well.
i  have a last question please:
I tried to run videoDepthEstimation.py but i have errors in  videoPafy = pafy.new(videoUrl) 
![image](https://user-images.githubusercontent.com/10595916/178019785-44dc3b10-4fa4-4961-bf3f-1b120ee5a5da.png)
Can you please give me a link to download the video because this link "https://www.youtube.com/watch?v=Yui48w71SG0" gives that:
![Capture](https://user-images.githubusercontent.com/10595916/178019484-1407df7c-f21e-4578-a87e-a3abfb1bf97f.PNG)

Thank you

**Comment by ibaiGorordo** [comment]
Yeah, that is a known issue with pafy. Install it again using this command:
`pip install git+https://github.com/zizo-pro/pafy@b8976f22c19e4ab5515cacbfae0a3970370c102b`

**Comment by chaimaOues** [comment]
i have this error with this command :ERROR: Error [WinError 2] Le fichier spécifié est introuvable while executing command git version ERROR: Cannot find command 'git' - do you have 'git' installed and in your PATH?

**Comment by ibaiGorordo** [comment]
I see, you need to install git to do that. You can either try to install git and retry it.

Or, if you know where pafy is installed, you can search for `backend_youtube_dl.py` in your computer and comment the dislike line `#self._dislikes = self._ydl_info.get('dislike_count', 0)` as in: https://github.com/mps-youtube/pafy/pull/305/files

**Comment by chaimaOues** [comment]
i comment the dislike and i get this error: 
![image](https://user-images.githubusercontent.com/10595916/178026907-bc747414-fd73-4220-8eb9-f108d8e1af4f.png)

**Comment by ibaiGorordo** [comment]
There seems to be some extra text (Skip to text) at the beginning of `backend_youtube_dl.py`. Make sure that the only difference is that the dislike count line is commented.

**Comment by chaimaOues** [comment]
it works. thank you very much for your help sir .
![image](https://user-images.githubusercontent.com/10595916/178031527-2a9552d7-f037-4522-8707-e88927efa81e.png)
